-- SQL statements to populate the 'products' table for NovelNest & Stationery Hub
-- Auto-generated from novelnest_frontend/products.php JavaScript array.

-- IMPORTANT:
-- 1. Ensure your 'categories' and 'subcategories' tables are populated with corresponding data.
-- 2. To link products to categories/subcategories, you will need to manually update
--    the category_id and subcategory_id columns in the 'products' table
--    after inserting this data, or populate them via another script.
--    The current SQL sets these to NULL, as per the foreign key constraint 'ON DELETE SET NULL'.

-- TRUNCATE TABLE products; -- Uncomment this line if you want to clear existing product data before inserting.

INSERT INTO products (product_id, name, description, price, stock, image_url, category_id, subcategory_id, created_at) VALUES
(1, 'Charcoal Pencil Set - 12pcs (Soft)', 'High-quality charcoal pencil set for artists.', 450.00, 100, 'images/art_supplies/drawing/Charcoal_Pencil_Set_12pcs_Soft.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(2, 'Colour Pencils', 'Vibrant colored pencils for all your artistic needs.', 300.00, 100, 'images/art_supplies/drawing/colour_pensils.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(3, 'Crayons', 'Classic wax crayons for kids and artists.', 250.00, 100, 'images/art_supplies/drawing/crayons.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(4, 'Oil Pastels', 'Soft and blendable oil pastels for rich color.', 350.00, 100, 'images/art_supplies/drawing/oil_pastels.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(5, 'Sketch Pens', 'Set of colorful sketch pens for drawing and outlining.', 280.00, 100, 'images/art_supplies/drawing/sketch_pens.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(6, 'Acrylic Paint Set 24 Colours 36ml', 'A comprehensive set of 24 acrylic paints for diverse projects.', 1200.00, 100, 'images/art_supplies/painting/Acrylic_Paint_Set_24_Colours_36ml.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(7, 'Marker Set', 'Assorted marker set for illustrations and coloring.', 600.00, 100, 'images/art_supplies/painting/marker_set.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(8, 'Paint Brushes', 'Variety pack of paint brushes for different painting techniques.', 500.00, 100, 'images/art_supplies/painting/paint_brushes.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(9, 'Water Colours', 'High-quality watercolor paint set for expressive artwork.', 400.00, 100, 'images/art_supplies/painting/water_colours.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(10, 'Wooden Palette', 'Traditional wooden palette for mixing paints.', 300.00, 100, 'images/art_supplies/painting/Wooden_Palette.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(11, 'Can We Be Strangers Again', 'A captivating fantasy novel.', 700.00, 100, 'images/novels/fantasy/can_we_be_strangers_again.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(12, 'Everything I Never Told You', 'An enthralling fantasy story.', 750.00, 100, 'images/novels/fantasy/everything_i_never_told_you.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(13, 'Meet Me in Another Life', 'A unique fantasy romance.', 720.00, 100, 'images/novels/fantasy/meet_me_in_another_life.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(14, 'Things I Wanted To Say', 'A thought-provoking fantasy read.', 680.00, 100, 'images/novels/fantasy/things_i_wanted_to_say.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(15, 'You Have To Choose What You Wanna Believe', 'A compelling fantasy narrative.', 700.00, 100, 'images/novels/fantasy/you_have_to_choose.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(16, 'Never Lie', 'A gripping fiction novel.', 800.00, 100, 'images/novels/fiction/Never_Lie.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(17, 'The Inmate', 'A suspenseful fiction thriller.', 850.00, 100, 'images/novels/fiction/The_Inmate.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(18, 'The Perfect Son', 'A dramatic fiction story.', 820.00, 100, 'images/novels/fiction/The_Perfect_Son.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(19, 'The Silent Patient', 'A psychological fiction masterpiece.', 900.00, 100, 'images/novels/fiction/The_Silent_Patient.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(20, 'The Wife Upstairs', 'A modern gothic fiction tale.', 780.00, 100, 'images/novels/fiction/The_Wife_Upstairs.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(21, 'Five Survive', 'A tense mystery novel.', 750.00, 100, 'images/novels/mystery/five_survive.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(22, 'One Of Us Is Lying', 'A high-stakes mystery for young adults.', 700.00, 100, 'images/novels/mystery/one_of_us_is_lying.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(23, 'The Girls Who Disappeared', 'An intriguing mystery with twists.', 770.00, 100, 'images/novels/mystery/The_girls_who_disappeared.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(24, 'The Perfect Marriage', 'A domestic mystery full of secrets.', 820.00, 100, 'images/novels/mystery/the_perfect_marriage.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(25, 'Then She Was Gone', 'A heartbreaking and suspenseful mystery.', 790.00, 100, 'images/novels/mystery/Then_She_Was_Gone.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(26, 'None of This Is True', 'A chilling nonfiction-style narrative.', 760.00, 100, 'images/novels/nonfiction/None_of_This_Is_True.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(27, 'Not Quite Dead Yet', 'A humorous nonfiction exploration of life.', 780.00, 100, 'images/novels/nonfiction/Not_Quite_Dead_Yet.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(28, 'Rock Paper Scissors', 'A thrilling nonfiction account.', 740.00, 100, 'images/novels/nonfiction/Rock_Paper_Scissors.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(29, 'The Only One Left', 'A suspenseful nonfiction read.', 800.00, 100, 'images/novels/nonfiction/The_Only_One_Left.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(30, 'The Silent Patient (Nonfiction)', 'A true-crime inspired nonfiction book.', 900.00, 100, 'images/novels/nonfiction/The_Silent_Patient.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(31, 'Confess', 'A deeply emotional romance novel.', 700.00, 100, 'images/novels/romance/confess.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(32, 'It Starts With Us', 'A heartwarming contemporary romance.', 850.00, 100, 'images/novels/romance/It_Starts_With_Us.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(33, 'November 9', 'A poignant romance about fate and choices.', 780.00, 100, 'images/novels/romance/November_9.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(34, 'Twisted Love', 'A dark and passionate romance.', 900.00, 100, 'images/novels/romance/Twisted_Love.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(35, 'Ugly Love', 'An intense and raw romance story.', 820.00, 100, 'images/novels/romance/Ugly_Love.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(36, 'Plot Twists I Didn’t See Coming', 'A thrilling page-turner with unexpected turns.', 880.00, 100, 'images/novels/thriller/Plot_Twists.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(37, 'The Co-Worker', 'A corporate thriller with high stakes.', 790.00, 100, 'images/novels/thriller/the_co_worker.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(38, 'The Gift', 'A psychological thriller with a dark secret.', 750.00, 100, 'images/novels/thriller/The_Gift.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(39, 'The Housemaid', 'A domestic thriller that will keep you guessing.', 830.00, 100, 'images/novels/thriller/The_Housemaid.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(40, 'The Tenant', 'A chilling thriller about a new tenant.', 800.00, 100, 'images/novels/thriller/The_Tenant.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(41, 'Coloured Manilla Paper', 'Assorted colored manilla paper for crafts and projects.', 150.00, 100, 'images/office_school_supplies/books_paper/coloured_manilla_paper.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(42, 'Envelopes', 'Standard white envelopes for office and personal use.', 100.00, 100, 'images/office_school_supplies/books_paper/Envelopes.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(43, 'Pattern Cutting Manilla Paper', 'Specialized manilla paper for pattern cutting.', 180.00, 100, 'images/office_school_supplies/books_paper/pattern_cutting_manilla.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(44, 'JK Copier A4 Paper', 'High-quality A4 copier paper for printers.', 500.00, 100, 'images/office_school_supplies/books_paper/JK_Copier_Paper.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(45, 'Notebook', 'Lined notebook for school or office use.', 120.00, 100, 'images/office_school_supplies/books_paper/notebook.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(46, 'Sketchbook', 'Blank sketchbook for drawing and creative expression.', 200.00, 100, 'images/office_school_supplies/books_paper/Sketchbook.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(47, 'Surard Notebook', 'Premium Surard brand notebook.', 140.00, 100, 'images/office_school_supplies/books_paper/Surard_notebook.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(48, 'Uni Foolscap Paper', 'Quality foolscap paper for various writing needs.', 180.00, 100, 'images/office_school_supplies/books_paper/Uni_Foolscap_Paper.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(49, 'Desk Organizer Tray', 'Multi-compartment desk organizer for office supplies.', 600.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Desk_Organizer.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(50, 'Scientific Calculator', 'Advanced scientific calculator for students and professionals.', 1500.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Calculator.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(51, 'Flexible Ruler', 'Bendable ruler for measuring curved surfaces.', 80.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Flexible_Ruler.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(52, 'Glue Stick', 'Non-toxic glue stick for paper crafts.', 90.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Glue_Stick.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(53, 'Mathematical Set', 'Complete mathematical geometry set.', 250.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Mathematical_set.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(54, 'Paper Binder Clips', 'Assorted sizes of binder clips for documents.', 180.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Binder_Clips.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(55, 'Paper Punch', 'Two-hole paper punch for filing documents.', 300.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Paper_Punch.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(56, 'Rubber Eraser', 'Soft rubber eraser for pencils.', 50.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Rubber.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(57, 'Scissors', 'Sharp, durable scissors for various cutting tasks.', 180.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Scissors.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(58, 'Sharpener', 'Pencil sharpener for standard and jumbo pencils.', 40.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Sharpener.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(59, 'Stapler', 'Desk stapler with staple remover.', 200.00, 100, 'images/office_school_supplies/measuringtools_deskitems/Stapler.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(60, '12 Set Pencils', 'Set of 12 graphite pencils for drawing and writing.', 120.00, 100, 'images/office_school_supplies/writing/12_set_pencils.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(61, 'Blue Bic Pen', 'Reliable blue Bic ballpoint pen.', 50.00, 100, 'images/office_school_supplies/writing/Blue_bic_pen.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(62, 'Black Bic Pen', 'Smooth-writing black Bic ballpoint pen.', 50.00, 100, 'images/office_school_supplies/writing/Black_bic_pen.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(63, 'Correction Fluid', 'Quick-drying correction fluid for errors.', 120.00, 100, 'images/office_school_supplies/writing/Correction_Fluid.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(64, 'Fountain Pens', 'Elegant fountain pens for a sophisticated writing experience.', 350.00, 100, 'images/office_school_supplies/writing/Fountain_Pens.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(65, 'Highlighter', 'Fluorescent highlighter for marking important text.', 90.00, 100, 'images/office_school_supplies/writing/highlighter.jpeg', NULL, NULL, CURRENT_TIMESTAMP),
(66, 'Red Pen', 'Standard red ballpoint pen for corrections or emphasis.', 50.00, 100, 'images/office_school_supplies/writing/Red_pen.jpeg', NULL, NULL, CURRENT_TIMESTAMP);